- admin/partials/instawp-admin-settings.php
- includes/class-instawp-ajax.php
- includes/class-instawp-rest-api.php
- includes/class-instawp.php
Latest Code with Rest api responses and hash, Heartbeat cron, settings save changes.
> Rest api, Heartbeat cron, Settings

- includes/class-instawp-ajax.php
- includes/class-instawp.php
Modified the logic for detecting the plugin on autologin hook.
> Autologin code changes for plugin activation detection

- includes/class-instawp-ajax.php
- includes/class-instawp-rest-api.php
- includes/class-instawp-restore-site.php
- includes/class-instawp-restore.php
- includes/class-instawp-zipclass.php
- includes/class-instawp.php
Modified Logs placed into restore on stage and  restore on production. Also added option for progress on restore api call from cloud.
> Modified Logs placed

- includes/class-instawp-rest-api.php
> implement clear cache api

- includes/class-intawp-ajax-fn.php
Minor Change - Edit Connect ID & Parent ID
> Minor Change - Edit Connect ID & Parent ID

- admin/class-instawp-admin.php
- admin/partials/instawp-admin-change-event.php
- includes/class-instawp-db.php
- includes/class-instawp-rest-apis.php
- includes/class-intawp-ajax-fn.php
hide sync options,id dynamic in sync_update,only pending events show
> hide sync options,id dynamic in sync_update,only pending events show

- admin/css/instawp-change-event.css
- admin/js/instawp-change-event.js
- admin/partials/instawp-admin-change-event.php
- includes/class-instawp-db.php
- includes/class-instawp-rest-apis.php
- includes/class-intawp-ajax-fn.php
selected events sync and custom post sync tested
> selected events sync and custom post sync tested

- instawp-connect.php
Clickup: https://app.clickup.com/t/85zrhy3tg
> stop redirecting on bulk plugin activation

- admin/css/instawp-change-event.css
- admin/js/instawp-change-event.js
- admin/partials/instawp-admin-change-event-filters.php
- admin/partials/instawp-admin-change-event.php
- includes/class-instawp-rest-apis.php
change event admin page changes
> change event admin page changes

- includes/class-instawp-rest-api.php
- instawp-connect.php
Clickup: https://app.clickup.com/t/85zrjxwgd
> add ability to download github plugin

- admin/partials/instawp-admin-change-event-filters.php
- includes/class-instawp-rest-apis.php
astra theme changes and woocommerce att create update delete
> astra theme changes and woocommerce att create update delete

- admin/partials/instawp-admin-change-event-filters.php
- includes/class-instawp-rest-apis.php
- includes/class-intawp-ajax-fn.php
> some issues fixed

- admin/class-instawp-admin.php
- admin/css/instawp-change-event.css
- admin/js/instawp-change-event.js
- admin/partials/instawp-admin-change-event-filters.php
- admin/partials/instawp-admin-change-event.php
- includes/class-instawp-db.php
- includes/class-instawp-rest-apis.php
- includes/class-intawp-ajax-fn.php
> Dev zile p2

- includes/class-instawp-rest-api.php
> added new inventory endpoint

- includes/class-instawp-rest-api.php
- includes/class-instawp-wp-config.php
Added DELETE endpoint for configuration management.
Added GET endpoint for debug logs.
Added non-defined constants in GET configuration endpoint.
Added Array value support in POST /configuration endpoint.
Added non allowed constants.
> Added Changes

- .distignore
- .gitignore
- gulpfile.js
- includes/class-instawp-database-management.php
- includes/class-instawp-file-management.php
- includes/class-instawp-rest-api.php
- includes/class-instawp-tools.php
- includes/class-instawp.php
- includes/database-manager/loader.php
- includes/file-manager/custom.css
- languages/instawp-connect.pot
- package-lock.json
- package.json
Updated gitignore
Updated disignore
Added Database Management endpoint.
Setup gulp file to create zip easily.
npm install
gulp
Added reusable auto login page code in class-instawp.php file.
Added language pot file using gulp.
> Remote management features

- includes/class-instawp-rest-api.php
- languages/instawp-connect.pot
WordPress Cache / Object Cache Plugins (e.g. [Radis Cache](https://wordpress.org/plugins/redis-cache/)/[Object Cache Pro](https://objectcache.pro/), [Docket Cache](https://wordpress.org/plugins/docket-cache/))
[WP Rocket](https://wp-rocket.me/)
[Autoptimize](https://wordpress.org/plugins/autoptimize/)
[W3 Total Cache](https://wordpress.org/plugins/w3-total-cache/)
[LiteSpeed Cache](https://wordpress.org/plugins/litespeed-cache/)
[WP Fastest Cache](https://wordpress.org/plugins/wp-fastest-cache/)
[WP Super Cache](https://wordpress.org/plugins/wp-super-cache/)
[Cache Enabler](https://wordpress.org/plugins/cache-enabler/)
[Hyper Cache](https://wordpress.org/plugins/hyper-cache/)
[Breeze](https://wordpress.org/plugins/breeze/)
[Comet Cache](https://wordpress.org/plugins/comet-cache/) …
> added cache plugins support

- admin/css/instawp-change-event.css
- includes/class-instawp-ajax.php
- includes/class-instawp-backup.php
- includes/class-instawp-setting.php
- includes/class-instawp.php
- includes/functions.php
- instawp-connect.php
- languages/instawp-connect.pot
- migrate/assets/css/style.css
- migrate/assets/js/scripts.js
- migrate/class-instawp-migrate.php
- migrate/templates/part-create.php
- migrate/templates/part-sites.php
- uninstall.php
`is_insta_site` flag support.
Files and Directory listing.
Larrge Files display and option to exclude them.
> added file list

- admin/js/instawp-change-event.js
- includes/class-instawp-ajax.php
- includes/sync/class-instawp-sync-ajax.php
- languages/instawp-connect.pot
- migrate/templates/part-sync.php
[sync all, sync selected](https://github.com/InstaWP/instawp-connect/pull/226/commits/16a19af5cceaee27a592099d6836b83ec6404326)
> Two way sync

- includes/class-instawp-curl.php
- includes/functions.php
- includes/sync/class-instawp-sync-ajax.php
- includes/sync/class-instawp-sync-apis.php
- includes/sync/class-instawp-sync-customizer.php
- includes/sync/class-instawp-sync-helpers.php
- includes/sync/class-instawp-sync-wc.php
- instawp-connect.php
- languages/instawp-connect.pot
- serve.php
Install sync tables only when needed
Heartbeat disable after 10 failures
> Install sync tables only when needed

- assets/js/scripts.js
- includes/class-instawp-ajax.php
- migrate/templates/part-create-staging.php
https://app.clickup.com/t/86cwdweyf
[Before](https://t1868024.p.clickup-attachments.com/t1868024/91e8f552-4b58-4e0f-8615-bf12827b6f75/image.png)
[Now](https://t1868024.p.clickup-attachments.com/t1868024/146d2dd8-f2be-49b7-83dd-5ab68d22ca95/image.png)
> fix staging creation display error

- includes/class-instawp-tools.php
- migrate/templates/part-create-staging.php
> Fix text left alignment in confirmation-warning light green section

- includes/class-instawp-tools.php
- includes/sync/class-instawp-sync-helpers.php
- includes/sync/class-instawp-sync-wc.php
- readme.txt
- New: Sync WooCommerce order notes.
- FIX: Sync WooCommerce product variant.
- FIX: Sync WooCommerce order item meta.
- NEW: Disable WooCommerce email for WooCommerce data sync.
> woocommerce order details sync

- includes/sync/class-instawp-sync-plugin-theme.php
- readme.txt
Fixed following Warnings
- PHP Warning:  Undefined array key 0 in /home/nudagevezu4261/web/tough-mosquito-dc9eb6.a.instawpsites.com/public_html/wp-content/plugins/instawp-connect/includes/sync/class-instawp-sync-plugin-theme.php on line 329
- PHP Warning:  Trying to access array offset on value of type null in /home/nudagevezu4261/web/tough-mosquito-dc9eb6.a.instawpsites.com/public_html/wp-content/plugins/instawp-connect/includes/sync/class-instawp-sync-plugin-theme.php on line 331
- PHP Warning:  Trying to access array offset on value of type null in /home/nudagevezu4261/web/tough-mosquito-dc9eb6.a.instawpsites.com/public_html/wp-content/plugins/instawp-connect/includes/sync/class-instawp-sync-plugin-theme.php on line 332
> FIX: Sync plugin and theme update php error

- includes/sync/class-instawp-sync-parser.php
- includes/sync/class-instawp-sync-post.php
- readme.txt
[Task](https://app.clickup.com/t/86cxktd7e)
> Added: FSE Theme Global Styles, Templates, Template parts sync support

- includes/apis/class-instawp-rest-api.php
- includes/functions.php
- includes/sync/class-instawp-sync-ajax.php
- includes/sync/class-instawp-sync-apis.php
- includes/sync/class-instawp-sync-helpers.php
- includes/sync/class-instawp-sync-parser.php
- languages/instawp-connect.pot
- readme.txt
- NEW: Dynamic sync batch size adjustment.
- Added: Media import from source with sync server fallback on errors.
- Fix: Prevent duplicate image uploads during sync.
> 86cxe28pm fix 429 error upload attachment api call

- includes/sync/class-instawp-sync-ajax.php
- includes/sync/class-instawp-sync-apis.php
- readme.txt
2 Way Sync - Event receiver status never get completed - add exception handling
https://app.clickup.com/t/86cxkz41z
> Added: Exception handling in events receiver API

- includes/sync/class-instawp-sync-ajax.php
- readme.txt
Fix memory limit exhaust issue by adding LIMIT and OFFSET in query
> #86cy1muyx Optimized query for fetching sync events

- includes/class-instawp-database-management.php
- includes/database-manager/loader.php
- readme.txt
- vendor/composer/installed.json
- vendor/composer/installed.php
- vendor/instawp/connect-helpers/src/DatabaseManager.php
Updated the Adminer database manager to version 5.3.0 and improved security by sanitizing file names and restricting template access to users with 'manage_options' capability. Also, updated the Adminer URL and modified the file handling logic to ensure better compatibility and security.
> feat(database-manager): update Adminer to v5.3.0 and enhance security

- includes/database-manager/loader.php
- vendor/composer/installed.json
- vendor/composer/installed.php
- vendor/instawp/connect-helpers/src/DatabaseManager.php
Update the Adminer URL to use the correct file name and remove unnecessary CSS styles in the loader.php file. This improves the functionality and readability of the code.
> refactor(database-manager): update Adminer URL and clean up CSS styles

- includes/apis/class-instawp-rest-api-migration.php
- includes/class-instawp-tools.php
- iwp-dest/index.php
- readme.txt
- Added: Migration support without requiring Connects
- Updated: instawp_last_migration_details option post plugin installation
- Updated: Excluded wp-settings.php for WP Cloud migrations
- Fixed: Corrected siteurl after migration
> exclude wp-settings.php file migration for wp cloud

- includes/apis/class-instawp-rest-api-migration.php
- includes/class-instawp-tools.php
- instawp-connect.php
- languages/instawp-connect.pot
- readme.txt
- Fixed: Removed migration helper plugins after migration.
- Fixed: Excluded migration helper plugins from migration.
> Removed migration helper plugins after migration
